baseURL = "https://joemizzi.com/"
languageCode = "en-us"
title = "Mizzi"

# RSS Configuration
rssLimit = 100

# Output formats
[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "search-index"
    isPlainText = true
    notAlternative = true
    
[outputs]
  home = ["HTML", "RSS", "SearchIndex"]
