baseURL = "https://joemizzi.com/"
locale = "en-US"
title = "Mizzi"
enableEmoji = true
rssLimit = 100

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "search-index"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = false
    noClasses = false
