description = "Music, Software, Midwest"
profile_image = "images/profile-large.png"

# Author information for RSS
[author]
  name = "Joe Mizzi"
  email = "joe@joemizzi.com"

[[social_links]]
name = "github"
href = "https://github.com/themizzi"
order = 200

[[social_links]]
name = "linkedin"
href = "https://linkedin.com/in/joemizzi"
order = 175

[[social_links]]
name = "goodreads"
href = "https://www.goodreads.com/user/show/51946425-joe-mizzi"
order = 600

[[social_links]]
name = "bluesky"
href = "https://bsky.app/profile/themizzinator.bsky.social"
order = 100

[[social_links]]
name = "signal-messenger"
href = "https://signal.me/#eu/RsNPXENWoya3LPHxYNQux0DR4C_REl1o1cyMPbNbxCT6YXFHBsdERbejvtdNMw5Z"
order = 650

[[social_links]]
name = "rss"
href = "/index.xml"
order = 700

# Search configuration
[search]
excludedTypes = ["credit"]
