baseURL = 'https://joemizzi.com/'
languageCode = 'en-us'
title = 'Joe Mizzi'
[params]
  short_description = "Music, Software, Midwest"
  large_profile_image = "images/profile-large.png"
  small_profile_image = "images/profile-small.png"
[[params.social_links]]
  name = "mastodon"
  href = "https://mastodon.social/@themizzi"
  order = 550
[[params.social_links]]
  name = "github"
  href = "https://github.com/themizzi"
  order = 200
[[params.social_links]]
  name = "linkedin"
  href = "https://linkedin.com/in/joemizzi"
  order = 300
[[params.social_links]]
  name = "facebook"
  href = "https://facebook.com/themizzi"
  order = 400
[[params.social_links]]
  name = "instagram"
  href = "https://instagram.com/themizzinator"
  order = 500
[[params.social_links]]
  name = "goodreads"
  href = "https://www.goodreads.com/user/show/51946425-joe-mizzi"
  order = 600
[[params.social_links]]
  name = "telegram"
  href = "https://t.me/themizzinator"
  order = 700
[[params.social_links]]
  name = "bluesky"
  href = "https://bsky.app/profile/themizzinator.bsky.social"
  order = 100
