name: "personal-site"
static_sites:
- github:
    repo: themizzi/themizzi.github.io
    branch: main
    deploy_on_push: true
  name: site
  source_dir: /
  dockerfile_path: ./Dockerfile
  output_dir: /workspace/public
  envs:
  - key: IMAGE_TAG
    value: ${IMAGE_TAG}
    scope: BUILD_TIME
domains:
- domain: joemizzi.com
  type: PRIMARY
  wildcard: true
