name: 'Deploy to Digital Ocean'
description: 'Deploy application to Digital Ocean App Platform'
inputs:
  token:
    description: 'Digital Ocean access token'
    required: true
  app-id:
    description: 'Digital Ocean App ID'
    required: true
  deploy-pr-preview:
    description: 'Whether to deploy PR preview'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Deploy the app
      id: deploy
      uses: digitalocean/app_action/deploy@v2
      with:
        token: ${{ inputs.token }}
        project_id: ${{ inputs.app-id }}
        print_build_logs: true
        print_deploy_logs: true
        deploy_pr_preview: ${{ inputs.deploy-pr-preview }}

outputs:
  app:
    description: 'Deployment output from Digital Ocean'
    value: ${{ steps.deploy.outputs.app }}
