name: 'Deploy to Digital Ocean'
description: 'Deploy application to Digital Ocean App Platform with GitHub Deployments API integration'
inputs:
  token:
    description: 'Digital Ocean access token'
    required: true
  app-id:
    description: 'Digital Ocean App ID'
    required: true
  deploy-pr-preview:
    description: 'Whether to deploy PR preview'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for deployment status updates'
    required: false
  deployment-id:
    description: 'GitHub deployment ID to update status for'
    required: false
  environment:
    description: 'Deployment environment name'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Update deployment status to in progress
      if: inputs.deployment-id && inputs.github-token
      uses: ./.github/actions/github-deployment
      with:
        github-token: ${{ inputs.github-token }}
        deployment-id: ${{ inputs.deployment-id }}
        action: 'update-status'
        status: 'in_progress'

    - name: Deploy the app
      id: deploy
      uses: digitalocean/app_action/deploy@v2
      with:
        token: ${{ inputs.token }}
        project_id: ${{ inputs.app-id }}
        print_build_logs: true
        print_deploy_logs: true
        deploy_pr_preview: ${{ inputs.deploy-pr-preview }}

    - name: Extract deployment URL
      id: extract-url
      if: success() && steps.deploy.outputs.app
      shell: bash
      run: |
        app_json='${{ steps.deploy.outputs.app }}'
        if [ -n "$app_json" ] && echo "$app_json" | jq -e . >/dev/null 2>&1; then
          live_url=$(echo "$app_json" | jq -r '.live_url // empty')
          echo "live-url=$live_url" >> $GITHUB_OUTPUT
          echo "Deployment URL: $live_url"
        else
          echo "Warning: Could not extract deployment URL from Digital Ocean output"
          echo "live-url=" >> $GITHUB_OUTPUT
        fi

    - name: Update deployment status to success
      if: success() && inputs.deployment-id && inputs.github-token
      uses: ./.github/actions/github-deployment
      with:
        github-token: ${{ inputs.github-token }}
        deployment-id: ${{ inputs.deployment-id }}
        action: 'update-status'
        status: 'success'
        deployment-url: ${{ steps.extract-url.outputs.live-url }}

    - name: Update deployment status to failure
      if: failure() && inputs.deployment-id && inputs.github-token
      uses: ./.github/actions/github-deployment
      with:
        github-token: ${{ inputs.github-token }}
        deployment-id: ${{ inputs.deployment-id }}
        action: 'update-status'
        status: 'failure'

outputs:
  app:
    description: 'Deployment output from Digital Ocean'
    value: ${{ steps.deploy.outputs.app }}
  deployment-url:
    description: 'URL of the deployed application'
    value: ${{ steps.extract-url.outputs.live-url }}
  deployment-id:
    description: 'GitHub deployment ID (passthrough)'
    value: ${{ inputs.deployment-id }}
