name: 'Run Playwright Tests'
description: 'Run Playwright tests in dev container and upload results'
inputs:
  artifact-name:
    description: 'Name for the test results artifact'
    required: false
    default: 'playwright-test-results'
  retention-days:
    description: 'Number of days to retain test results'
    required: false
    default: '7'
  image-tag:
    description: 'Docker image tag to use (defaults to latest)'
    required: false
    default: 'latest'
  push-image:
    description: 'Whether to push the container image (always, never, filter)'
    required: false
    default: 'never'

runs:
  using: 'composite'
  steps:
    - name: Log in to Container Registry
      if: inputs.push-image != 'never'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
        
    - name: Run tests in dev container
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/${{ github.repository }}/devcontainer
        imageTag: ${{ inputs.image-tag }}
        cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
        push: ${{ inputs.push-image }}
        runCmd: |
          cd themes/mizzi
          npm ci
          npm test
