name: Delete Preview

on:
# Run on all closed PRs
  pull_request:
    types: [ closed ]

permissions:
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete Digital Ocean preview app (from PR)
        uses: digitalocean/app_action/delete@v2
        with:
          from_pr_preview: true
          ignore_not_found: true
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
